version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'apilogin'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: db-login

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  pg-data:
          